# Generated by Django 5.1.3 on 2025-01-11 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('author_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_note', to=settings.AUTH_USER_MODEL)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intern', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
