# Generated by Django 5.1.3 on 2024-12-10 00:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(default=datetime.datetime.now)),
                ('deadline', models.DateField()),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=1000)),
                ('requirments', models.TextField(max_length=1000, null=True)),
                ('status', models.BooleanField()),
                ('task_end', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'task',
            },
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
    ]
